#!/usr/bin/env python3
"""Convert an indexed PNG planet strip into Mode 0 tiles, a tile map and a palette.

The image's palette index is the pen (0-15); its RGB picks the nearest CPC
hardware colour. A tile is one CRTC character: 4 Mode 0 pixels x 8 lines,
16 bytes stored line by line (2 bytes per line). The map is column-major,
one byte per cell, so a scroll step reads one contiguous column.

Usage: png2tiles.py in.png out_prefix
Writes out_prefix.tiles, out_prefix.map, out_prefix.pal and out_prefix.inc.
"""
import sys
from PIL import Image

from cpcpal import mode0_byte, nearest_hw

TILE_W, TILE_H = 4, 8


def convert(path):
    img = Image.open(path)
    if img.mode != "P":
        raise SystemExit(f"{path}: needs an indexed (P mode) image, got {img.mode}")
    w, h = img.size
    if w % TILE_W or h % TILE_H:
        raise SystemExit(f"{path}: size {w}x{h} is not a multiple of {TILE_W}x{TILE_H}")
    px = img.load()
    cols, rows = w // TILE_W, h // TILE_H

    tiles, index, cells = [], {}, []
    for cx in range(cols):
        for cy in range(rows):
            data = bytearray()
            for y in range(TILE_H):
                for x in range(0, TILE_W, 2):
                    a, b = px[cx * TILE_W + x, cy * TILE_H + y], px[cx * TILE_W + x + 1, cy * TILE_H + y]
                    if a > 15 or b > 15:
                        raise SystemExit(f"{path}: pen {max(a, b)} at ({cx * TILE_W + x},{cy * TILE_H + y}) is above 15")
                    data.append(mode0_byte(a, b))
            key = bytes(data)
            if key not in index:
                index[key] = len(tiles)
                tiles.append(key)
            cells.append(index[key])
    if len(tiles) > 256:
        raise SystemExit(f"{path}: {len(tiles)} unique tiles, the limit is 256")

    raw = img.getpalette()[:48]
    raw += [0] * (48 - len(raw))
    pal = bytes(nearest_hw(tuple(raw[i * 3:i * 3 + 3])) for i in range(16))
    return b"".join(tiles), bytes(cells), pal, cols, rows, len(tiles)


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    src, out = sys.argv[1:]
    tiles, cells, pal, cols, rows, n = convert(src)
    open(out + ".tiles", "wb").write(tiles)
    open(out + ".map", "wb").write(cells)
    open(out + ".pal", "wb").write(pal)
    with open(out + ".inc", "w") as f:
        f.write(f"; generated by png2tiles.py from {src}\n")
        f.write(f"MAP_COLS equ {cols}\nMAP_ROWS equ {rows}\nNUM_TILES equ {n}\n")
    print(f"{src}: {cols}x{rows} cells, {n} unique tiles")


if __name__ == "__main__":
    main()
