#!/usr/bin/env python3
"""Convert an indexed PNG planet strip into Mode 0 tiles, a tile map and a palette.

The image's palette index is the pen (0-15); its RGB picks the nearest CPC
hardware colour. A tile is one CRTC character: 4 Mode 0 pixels x 8 lines,
16 bytes stored line by line (2 bytes per line). The map is column-major,
one byte per cell, so a scroll step reads one contiguous column.

An optional foreground mask (same size; any non-zero pixel is foreground)
marks what is drawn over sprites. Each tile with foreground pixels gets an
overlay: 8 lines of (mask, pixels, mask, pixels), 32 bytes, applied as
screen = (screen AND mask) OR pixels. The attribute table gives each tile
its overlay number (1-255), or 0 for none, and the column table says which
map columns have any foreground (1) so whole sprites can skip the pass.

Usage: png2tiles.py in.png out_prefix [fg_mask.png]
Writes out_prefix.tiles, .map, .pal, .attr, .fg, .colfg and .inc.
"""
import sys
from PIL import Image

from cpcpal import mode0_byte, nearest_hw

TILE_W, TILE_H = 4, 8


def convert(path, fg_path=None):
    img = Image.open(path)
    if img.mode != "P":
        raise SystemExit(f"{path}: needs an indexed (P mode) image, got {img.mode}")
    w, h = img.size
    if w % TILE_W or h % TILE_H:
        raise SystemExit(f"{path}: size {w}x{h} is not a multiple of {TILE_W}x{TILE_H}")
    px = img.load()
    fg = None
    if fg_path:
        fg_img = Image.open(fg_path)
        if fg_img.size != img.size:
            raise SystemExit(f"{fg_path}: size {fg_img.size} differs from {path}")
        fg = fg_img.load()
    cols, rows = w // TILE_W, h // TILE_H

    tiles, overlays, attrs, index, cells = [], [], [], {}, []
    for cx in range(cols):
        for cy in range(rows):
            data, over = bytearray(), bytearray()
            has_fg = False
            for y in range(TILE_H):
                for x in range(0, TILE_W, 2):
                    gx, gy = cx * TILE_W + x, cy * TILE_H + y
                    a, b = px[gx, gy], px[gx + 1, gy]
                    if a > 15 or b > 15:
                        raise SystemExit(f"{path}: pen {max(a, b)} at ({gx},{gy}) is above 15")
                    data.append(mode0_byte(a, b))
                    fa = bool(fg and fg[gx, gy])
                    fb = bool(fg and fg[gx + 1, gy])
                    has_fg |= fa or fb
                    mask = (0 if fa else 0xAA) | (0 if fb else 0x55)
                    over += bytes([mask, mode0_byte(a if fa else 0, b if fb else 0)])
            key = (bytes(data), bytes(over) if has_fg else None)
            if key not in index:
                index[key] = len(tiles)
                tiles.append(key[0])
                if has_fg:
                    overlays.append(key[1])
                    attrs.append(len(overlays))
                else:
                    attrs.append(0)
            cells.append(index[key])
    if len(tiles) > 256:
        raise SystemExit(f"{path}: {len(tiles)} unique tiles, the limit is 256")
    if len(overlays) > 255:
        raise SystemExit(f"{path}: {len(overlays)} foreground tiles, the limit is 255")

    raw = img.getpalette()[:48]
    raw += [0] * (48 - len(raw))
    pal = bytes(nearest_hw(tuple(raw[i * 3:i * 3 + 3])) for i in range(16))
    attr = bytes(attrs) + bytes(256 - len(attrs))
    colfg = bytes(int(any(attrs[cells[c * rows + r]] for r in range(rows))) for c in range(cols))
    return (b"".join(tiles), bytes(cells), pal, attr, b"".join(overlays), colfg,
            cols, rows, len(tiles), len(overlays))


def main():
    if len(sys.argv) not in (3, 4):
        raise SystemExit(__doc__)
    src, out = sys.argv[1:3]
    fg = sys.argv[3] if len(sys.argv) == 4 else None
    tiles, cells, pal, attr, over, colfg, cols, rows, n, nfg = convert(src, fg)
    for ext, data in ((".tiles", tiles), (".map", cells), (".pal", pal),
                      (".attr", attr), (".fg", over), (".colfg", colfg)):
        open(out + ext, "wb").write(data)
    with open(out + ".inc", "w") as f:
        f.write(f"; generated by png2tiles.py from {src}\n")
        f.write(f"MAP_COLS equ {cols}\nMAP_ROWS equ {rows}\nNUM_TILES equ {n}\n")
        f.write(f"NUM_FG_TILES equ {nfg}\n")
    print(f"{src}: {cols}x{rows} cells, {n} unique tiles, {nfg} with foreground")


if __name__ == "__main__":
    main()
