#!/usr/bin/env python3
"""Convert a sprite sheet into pre-shifted Mode 0 sprite data.

Each frame (listed in the JSON, in order) is stored twice: as drawn (W
bytes per line, W = width / 2) and shifted one pixel right (W + 1 bytes per
line), line after line. Pen 0 is transparent; the game derives masks from a
lookup table, so no mask bytes are stored.

Writes out_prefix.spr (the data), out_prefix.inc (an ID constant per frame,
SPR_<NAME>, and sizes) and out_prefix.frames (the frame table spr_frames,
6 bytes per frame: W, height, address of the unshifted data, address of the
shifted data, relative to the label sprite_data).

Usage: png2spr.py sheet.png frames.json out_prefix
"""
import json
import sys
from PIL import Image

from cpcpal import mode0_byte


def main():
    if len(sys.argv) != 4:
        raise SystemExit(__doc__)
    sheet, frames_json, out = sys.argv[1:]
    img = Image.open(sheet)
    px = img.load()
    frames = json.load(open(frames_json))
    data = bytearray()
    table = []
    for f in frames:
        w, h = f["w"], f["h"]
        if w % 2:
            raise SystemExit(f"{f['name']}: width {w} is odd")
        rows = [[px[f["x"] + x, f["y"] + y] for x in range(w)] for y in range(h)]
        offsets = []
        for shifted in (False, True):
            offsets.append(len(data))
            for row in rows:
                line = ([0] + row + [0]) if shifted else row
                for x in range(0, len(line), 2):
                    data.append(mode0_byte(line[x], line[x + 1]))
        table.append((f["name"], w // 2, h, offsets))
    open(out + ".spr", "wb").write(data)
    with open(out + ".inc", "w") as f:
        f.write(f"; generated by png2spr.py from {sheet}\n")
        for i, (name, *_ ) in enumerate(table):
            f.write(f"SPR_{name.upper()} equ {i}\n")
        f.write(f"NUM_SPRITE_FRAMES equ {len(table)}\n")
        f.write(f"SPR_MAX_W equ {max(t[1] for t in table) + 1}\n")
    with open(out + ".frames", "w") as f:
        f.write(f"; generated by png2spr.py from {sheet}\n")
        f.write("spr_frames:\n")
        for name, w, h, (o0, o1) in table:
            f.write(f"    db {w},{h} : dw sprite_data+{o0},sprite_data+{o1}  ; {name}\n")
    print(f"{sheet}: {len(table)} frames, {len(data)} bytes")


if __name__ == "__main__":
    main()
